main: org.samo_lego.clientstorage.spigot.ClientStorageSpigot
name: ${modName}
version: ${version}
description: This plugin allows you to limit some ClientStorage mod features. Licensed under LGPLv3.0.
author: samo_lego
website: https://github.com/samolego/ClientStorage
api-version: ${apiVersion}